#!/bin/bash

# requirements
# sqlite3
# exim-daemon-heavy v 4.64 (?) for named acl_m variables

function die() {
    echo $* >&2
    exit 1
}

SCRIPT=$(readlink -f ${BASH_SOURCE[0]})
HERE=$(dirname "$SCRIPT")
EXIM=/etc/exim4
USER=Debian-exim
GROUP=Debian-exim
WRITABLE=0750
READABLE=0644

function myinstall() {
    install -g root -o root -m $1 "$2" "$3"
}


SQLITE=sqlite3

export DISP_ALIASES_DB=/var/spool/exim4/db/disposable-aliases.db
export DISP_ALIASES_FILTER=$EXIM/conf.d/disposable-aliases-filter

if [[ "$FORCE" == "1" ]]; then
   rm -vf $DISP_ALIASES_DB
   $SQLITE "$DISP_ALIASES_DB" <"$HERE/schema.sql" || die "failed to install sqlite db"
elif [[ "$FORCE" == "0" ]]; then
   echo "Leaving as is: $DISP_ALIASES_DB"
elif [[ -e "$DISP_ALIASES_DB" ]]; then
   die "refusing to overwrite database $DISP_ALIASES_DB"
else
   $SQLITE "$DISP_ALIASES_DB" <"$HERE/schema.sql" || die "failed to install sqlite db"
fi

chown $USER:$GROUP "$DISP_ALIASES_DB"
chmod $WRITABLE "$DISP_ALIASES_DB" 

cat >"$EXIM/conf.d/main/00_local-macros" <<EOF
# This needs to be included before the routers

DISP_ALIASES_DB = $DISP_ALIASES_DB
DISP_ALIASES_FILTER = $DISP_ALIASES_FILTER
EOF

myinstall $READABLE "$HERE/router" "$EXIM/conf.d/router/450_local-disposable_aliases"

./expand-macros <"$HERE/filter" >"$HERE/filter2"
myinstall $READABLE "$HERE/filter2" "$DISP_ALIASES_FILTER"


service exim4 restart
