#!/bin/bash

# requirements
# sqlite3
# exim-daemon-heavy v 4.64 (?) for named acl_m variables

function die() {
    echo $* >&2
    exit 1
}

SCRIPT=$(readlink -f ${BASH_SOURCE[0]})
HERE=$(dirname "$SCRIPT")
EXIM=/etc/exim4
USER=Debian-exim
GROUP=Debian-exim
WRITABLE=0750
READABLE=0644

function myinstall() {
    install -g root -o root -m $1 "$2" "$3"
}


SQLITE=sqlite3

DISP_ALIASES_DB=/var/spool/exim4/db/disposable-aliases.db
DISP_ALIASES_CONTROLLER=/usr/bin/disposable-aliases-controller
CHECK_RCPT_LOCAL_ACL_FILE=$EXIM/local_disposable-aliases-include
CHECK_RCPT_LOCAL_ACL_PREAMBLE_FILE=$EXIM/local_disposable-aliases-preamble
DISP_ALIASES_FILTER=$EXIM/conf.d/disposable-aliases-filter

if [[ "$FORCE" == "1" ]]; then
   rm -vf $DISP_ALIASES_DB
elif [[ "$FORCE" == "0" ]]; then
   echo "Leaving as is: $DISP_ALIASES_DB"
elif [[ -e "$DISP_ALIASES_DB" ]]; then
   die "refusing to overwrite database $DISP_ALIASES_DB"
else
   $SQLITE "$DISP_ALIASES_DB" <"$HERE/schema.sql" || die "failed to install sqlite db"
fi

chown $USER:$GROUP "$DISP_ALIASES_DB"
chmod $WRITABLE "$DISP_ALIASES_DB" 

# FIXME copy exim configs
cat >"$EXIM/conf.d/main/00_local-macros" <<EOF
# This needs to be included before the acl and routers

DISP_ALIASES_DB = $DISP_ALIASES_DB
CHECK_RCPT_LOCAL_ACL_FILE = $CHECK_RCPT_LOCAL_ACL_FILE
CHECK_RCPT_LOCAL_ACL_PREAMBLE_FILE = $CHECK_RCPT_LOCAL_ACL_PREAMBLE_FILE
DISP_ALIASES_CONTROLLER = "|$DISP_ALIASES_CONTROLLER"
DISP_ALIASES_FILTER = $DISP_ALIASES_FILTER
EOF

cat >"$CHECK_RCPT_LOCAL_ACL_FILE" <<EOF
#include the disposable aliases acl
deny !acl = acl_disposable_aliases

EOF

# FIXME s/local-/local_/
myinstall $READABLE "$HERE/acl" "$EXIM/conf.d/acl/10_local-disposable_aliases"

myinstall $READABLE "$HERE/router" "$EXIM/conf.d/router/450_local-disposable_aliases"

#myinstall $READABLE "$HERE/controller" "$DISP_ALIASES_CONTROLLER"

myinstall $READABLE "$HERE/filter2" "$DISP_ALIASES_FILTER"

myinstall $READABLE "$HERE/acl-preamble" "$CHECK_RCPT_LOCAL_ACL_PREAMBLE_FILE"

# FIXME restart
